### ISSUE TITLE
Cant seem to get any search results

### ISSUE THREAD

**Issue by Sobodh-Jagaran** [spatie/googlesearch#12]
Hi I have set up google custom search and that seem work fine when i test it.

Now when i try to add it to mu laravel app using this package I'm not getting any results returned its just a empty array so i tried to test if it goes into the get results function  by adding a die statement and it doesn't seem to be.

//Code from your pakage
public function getResults($query)
    {
        die(print('im here')); // die statement to check if it reaches here
        $searchResults = [];

        if ($query == '') {
            return $searchResults;
        }

        if ($this->searchEngineId == '') {
            throw new \Exception('You must specify a searchEngineId');
        }

        $client = new Client();
        $result = $client->get('http://www.google.com/cse', ['query' => ['cx' => $this->searchEngineId,
                'client' => 'google-csbe',
                'num' => 20,
                'output' => 'xml_no_dtd',
                'q' => $query,
            ],
        ]);

        if ($result->getStatusCode() != 200) {
            throw new Exception('Resultcode was not ok: '.$result->getStatusCode());
        }

        $xml = simplexml_load_string($result->getBody());

        if ($xml->RES->R) {
            $i = 0;
            foreach ($xml->RES->R as $item) {
                $searchResults[$i]['name'] = (string) $item->T;
                $searchResults[$i]['url'] = (string) $item->U;
                $searchResults[$i]['snippet'] = (string) $item->S;
                $searchResults[$i]['image'] = $this->getPageMapProperty($item, 'cse_image', 'src');

                $searchResults[$i]['product']['name'] = $this->getPageMapProperty($item, 'product', 'name');
                $searchResults[$i]['product']['brand'] = $this->getPageMapProperty($item, 'product', 'brand');
                $searchResults[$i]['product']['price'] = $this->getPageMapProperty($item, 'product', 'price');
                $searchResults[$i]['product']['image'] = $this->getPageMapProperty($item, 'product', 'image');
                $searchResults[$i]['product']['identifier'] = $this->getPageMapProperty($item, 'product', 'identifier');

                $searchResults[$i]['offer']['price'] = $this->getPageMapProperty($item, 'offer', 'price');
                $searchResults[$i]['offer']['pricecurrency'] = $this->getPageMapProperty($item, 'offer', 'pricecurrency');

                ++$i;
            }
        }

        return $searchResults;
    }

// My serach method to call the getResults method.
public function search(Requests\SearchRequest $request)
    {
        $search = $request->all('search');
        $searchResults = GoogleSearch::getResults($search['search']);
      
        //die(print_r($searchResults));
    }

Could you tell me what I'm doing wrong!

**Comment by freekmurze** [comment]
Are you sure that `$search['search'` contains a value? Try testing with a simple string just to be sure.

**Comment by captainswain** [comment]
I'm having the same issue, i'm using Laravel 5.2 and can't seem to get it working..

I installed it using composer, set my search engine ID and can never get anything other than empty braces.

`  
$searchResults = GoogleSearch::getResults('a');

 dd($searchResults);`

The result is always an empty set [] regardless of the content and the query.. Not sure what to do anyone have tips?

**Comment by freekmurze** [comment]
I'll put a little note in the readme about this change.
