### ISSUE TITLE
Non-static method Spatie\GoogleSearch\GoogleSearch::getResults() should not be called statically

### ISSUE THREAD

**Issue by almamundinajpuri** [spatie/googlesearch#6]
Hello,
I'm getting this error when I try to follow your doc.
```Non-static method Spatie\GoogleSearch\GoogleSearch::getResults() should not be called statically```

If I create new instance of the class, it throws different error.
Could you help me here?

Regards

**Comment by freekmurze** [comment]
Probably you have imported the GoogleSearch-class in your class. You should import the facade.
Replace `use Spatie\GoogleSearch\GoogleSearch` by `use GoogleSearch` and try again.

**Comment by almamundinajpuri** [comment]
Thanks. It helped.
