### ISSUE TITLE
No results

### ISSUE THREAD

**Issue by almamundinajpuri** [spatie/googlesearch#8]
Hello,

I've tried it several times. Used old and new Google CSE id. But no result comes. Does it really work? 

Regards

**Comment by freekmurze** [comment]
With this little information on your error I can only say that yes, it works on my end. What do you mean by no results? Are you seeing an error message? Does GA responds with zeroes?

**Comment by almamundinajpuri** [comment]
Isn't Search API key also required?

**Comment by freekmurze** [comment]
It's not required.

**Comment by almamundinajpuri** [comment]
This package is for __Google Site Search__ which is a __paid service__, not for __Google CSE__ the free version.
https://developers.google.com/custom-search/docs/xml_results?hl=en

**Comment by freekmurze** [comment]
I tend to disagree :-) Like stated in the readme, this package integrates Google CSE in a Laravel app.
