### ISSUE TITLE
Guzzle 4.0 is EOL

### ISSUE THREAD

**Issue by devanes** [spatie/googlesearch#9]
Hello,
Guzzle 4.0 is end of life and no longer available, so you're package can't be installed (plus I use Guzzle 6. for my own functions).
Could you please update your package for Guzzle 6 (note that as far as I know the syntax for Guzzle has changed)?

Regards,
Martijn

**Comment by freekmurze** [comment]
The next time I need this package myself I'll give it an update. If you need support for Guzzle 6 soon, send a PR.

**Comment by devanes** [comment]
I did a quick check. Just updating the version number for example using >= is enough. The syntax you use hasn't changed. Do you still need the PR for that?

**Comment by freekmurze** [comment]
In that case, I'll test it myself in the coming days and tag the change.

**Comment by devanes** [comment]
Thanks! Can you let me know here once it's done? Then I can revert from my temporary clone to the regular package.

**Comment by freekmurze** [comment]
Sure, I'll let you know.

**Comment by freekmurze** [comment]
Support for Guzzle 6 has been added to the master branch. Will tag soon.

**Comment by freekmurze** [comment]
Tagged as version 2.0.2
